# Generated by Django 5.1.1 on 2024-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginusuario',
            name='verificacion_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
